### ISSUE TITLE
[Dregora - Issue] Rivers odd

### ISSUE THREAD

**Issue by Zygus42** [NLBlackEagle/Dregora#17]
* Minecraft version 1.12
* Dregora version 1.4, 1.5, 1.5.1
* Environment Type (Forge or Server such as Spigot) forge-1.12.2-14.23.5.2806-installer-win
* Steps to reproduce the problem Look in rivers

There are stretches along the rivers under the surface which are filled with air.  Pictures included:
![2019-02-02_12 58 23](https://user-images.githubusercontent.com/20757445/52324074-b4a8fa00-2a1a-11e9-9cc6-61cb42ac73cf.png)
![2019-02-02_12 58 30](https://user-images.githubusercontent.com/20757445/52324075-b5419080-2a1a-11e9-98fa-2534f7262f04.png)

Noticed a similar thing on another portion of the map where there are giant canyons with lava and water just hanging there instead of flowing down.  I think you need to do something to prompt liquid blocks to do a block update after they're done spawning in.  From experiences with other mods that spawn things in, same applies to blocks that provide light.

**Comment by TheOneKevin** [comment]
This issue is present when running on Spigot 1.12.2 with OTG

**Comment by alxcool** [comment]
I don't know if this issue is linked with an option in the config folder. Like 
RiverRarity: 8

RiverSize: 0

RiversEnabled: false

ImprovedRivers: false

RandomRivers: false

Once aigain on my older laptop running the previous minecraft launcher, this issue was not a thing... On the other hand. I've created for fun some vanilla maps and the collor or effect of such missing water block look amazing! Cheer up your mods are really amazing!
edit : I'm glad to meet an another consumer of plants2 mod!! I can't do without it :P

**Comment by NLBlackEagle** [comment]
Issue fixed as of v1.6.

Thanks for reporting this issue!!
