### ISSUE TITLE
[Dregora - Suggestion] Remove beacons from starting area

### ISSUE THREAD

**Issue by Zygus42** [NLBlackEagle/Dregora#18]
* Minecraft version 1.12
* Dregora version 1.5.1
* Environment Type (Forge or Server such as Spigot) forge-1.12.2-14.23.5.2806-installer-win
* Steps to reproduce the problem Start

I know that you just made the starting area larger and fancier, and I love the looks of the beacons, but from the point of view of starting a survival server there, the first thing someone is going to do is dig up the gold and the beacons.  Just the gold alone is enough to break the economy of a survival server, as it's 68 gold blocks or 612 gold ingots.  I have played minecraft games for a long time and not used as much as 612 gold ingots.  If you must have the beacons, at least remove the top ring of gold blocks that the beam passes through - can't see them anyway, and that would at least halve the amount.

**Comment by NLBlackEagle** [comment]
The Spawn was originality intended to be a starting safe zone where people wouldnt be able to break blocks which is why i can perfectly understand this suggestion. In the upcoming 2 weeks i Will spend time updating the existing structures to fix any issues like with Sapphire city not spawning in properly and changes like the beacons.

Expect Them to be removed in the next update :)

**Comment by NLBlackEagle** [comment]
Removed beacons as of 1.62
