### ISSUE TITLE
Mob spawn

### ISSUE THREAD

**Issue by VasperSi** [NLBlackEagle/Dregora#26]
Minecraft v. 1.12.2
Dregora v1.65

First sorry for my bad english :(

Hey, my issue is mob spawning. I just dowloaded this mod and its really cool. But in the biomes isn't spawning nearly any entity. Even the vanilla ones. 
I searched for config files and found the one with all biomes. I see, I can configorate every single biome's entity spawn, but there are... aaaaa loooot biomes. My question is, is there any simpler way to configorate? And not just open over 100 biomes and typing every single mob from every single mod I have.

I'm just new in modpack developing and trying to create something for me and my friends, so sorry if I ask a dump question. 

Thanks in advance!

**Comment by SamB440** [comment]
Are you on server or forge? If server, what are you using?

**Comment by VasperSi** [comment]
Hey, Im on forge, newest version for now.

**Comment by NLBlackEagle** [comment]
When you say entities, do you mean the default ones or the ones from a mod? It is already a while ago but I had tested it for Ice & Fire, Mo'sCreatures and Likanitemobs ( Apologies if I spell the mods wrong there ) discovered some issues, fixed them and tested it again with success.

If you use any of those in the modpack could you try loading up dregora with those or one of those mods to see if spawning works correctly with vanilla creatures included?

It might be that there is a mod non-compatible with OTG and somehow blocks the spawning of mobs in general. Thanks for reporting this anyhow, if it turns out to be something I can fix it's a step forward for the mod again :)a

**Mo's Creatures explaination:**
Edit: I just remembered mo's creatures having issues with world generators in general as it uses a strange spawning mechanism instead of hooking into what forge/minecraft has to offer. The best ways to fix these issues probably lie among the two following idea's;

1. adjusting all the biomes specifically for Mo's creatures and in the process break compatibility with a lot of other mods.
2. convincing someone to change the system mo's creatures is using to spawn in animals.

The way mo's creatures currently work is that the animals do spawn here and there but extremely rarely as they use the vanilla biomes instead of biometags to spawn stuff in which means it only works for non-virtual biomes. If you'd like to know more feel free to ask and I can try to explain how the whole virtual biomes stuff work ;)

**Comment by VasperSi** [comment]
I mean everything (vanilla, mods, creatures, monsters....). But like I said most dont work. "Ice and fire" works okay and animals from "BetterAnimalsPlus" are working. 
This is what dont work:
-Vanilla (Sheep, cow, Zombie and just everythink)
-Animania 
-DungeonMobs
-Fish's Undead Rising
-exotic birds (But not sure actually, have to test it again)
-Just a few fish

Aaaand I think this is all. I'm now not home, when I'm back, then I will send you picture with all my mods at the moment.
I know about Mo's creatures problems, so this is why I'm using now "BetterAnimalsPlus" and it's working fine.
When I'm back, I will try load Dregora with only the Entity mods to see what mod exactly is making this issue.

Thank you for fast response!

**Comment by VasperSi** [comment]
So I have tested all entities mods with just OTG and Dregora, then all together and finally with all my mods.

Check means it works.
Alone:

-Animania check
-BetterAnimalsPlus check
-dungeonMobs check (not found mod mobs, but /otg entities showed, they can spawn)
-exoticBirds check
-Fishs Undead Rising check (Rare monsters)
-Just a Few Fish check
-Lumen check (But Vanilla entities are rare)
-ice and fire check

All mods together:

    -Vanilla check (but rare)
    -BetterAnimalsPlus check
    -Animania check
    -DungeonMobs
    -ExoticBirds check
    -FishUndeadRising check
    -Just a few Fish
    -Lumen check
    -ice and fire check

Monster are very rare.
I find Animania creatures and Animania is changing the normal Vanilla, so I think vanilla creatures work, but monsters are somehow rare.

After all I tried with all my mods and dont find a lot of entities(besides ice and fire, exotic birds, BetterAnimalPlus.... so mostly creatures), but after a long jorney I manage to find some Zombies and Skeletons near the ocean. But they spawned only there. 
I think maybe the problem is using of to much entitiy mods (incompatibility of some mods) or the problem is in some of my mob setting mods like thiccentities for example.

Here pictures from mods I use.

![image](https://user-images.githubusercontent.com/66650078/84320344-cac84c80-ab71-11ea-81eb-70aa00b88e03.png)
![image](https://user-images.githubusercontent.com/66650078/84320422-ecc1cf00-ab71-11ea-97e3-42d47c56f518.png)
![image](https://user-images.githubusercontent.com/66650078/84320457-fc411800-ab71-11ea-9581-9e23cb12c70b.png)

**Comment by NLBlackEagle** [comment]
Perhaps it is worth a try to increase the amount of mobs that can spawn or count the current active entities. It could be that the regular animals out spawn the monsters.

In that light it would make sense that having too many entities mods would cause some issues. I am not entirely sure if it works like this but usually a spawning mechanism works with the following 3 values:

SpawnPool ( Total amount of mobs allowed which then again is divided into animals/mobs )
IndividualSpawnWeight ( the priority of a individual animal/mob )
IndididualPercentage ( The max/min allowed spawns per animal/mob )

So if something spawns then it is a X change it spawns an animal and X chance it spawns a mob. If it spawns a mob then it decided which mob in the list has the highest weight and then it spawns that mob unless the existing number exceeds the percentage allowed.

This is all theoretical as I don't know the inner workings but i shouldn't be far from it. There is a way to see if this is the case and that is checking how many of what type walks around and compare it with the maximum allowed number of animals/mobs. 

E.G. if you have 10 turkeys running around, 1 pig and something else for animals then its likely the turkey mod saturates the spawn pool :) 

[Update] I do know some mods replace the vanilla ones because its easier to do so, if you have 2 mods doing that then chances are that mod 1 steals all spawns from mod 2. If this is the case you could figure it out by switching some mods off/on and experiment with the results. A fast test of such is to pick the mod that has the least amount of visible spawns and remove all the other entity mods. If that mod suddenly starts spawning an abundance of mods then it might help to adjust some settings of the mods that "steal" the vanilla spawn setting such as a rarity of like 10% chance to replace vanilla spawns if the author added such a option.

**Comment by NLBlackEagle** [comment]
Love the fact way stones is in there by the way, I can believe that works pretty neat with Dregora 👍

**Comment by NLBlackEagle** [comment]
Latest version do not seem to have underspawning mods anymore. Perhaps it was one of the mods in the list?
