### ISSUE TITLE
Double world gen spawning

### ISSUE THREAD

**Issue by Merricide** [NLBlackEagle/Dregora#28]
#### Dregora Mod/Plugin
- [X] OTG Mod for Forge
- [ ] OTG Plugin for Spigot

#### Dregora Version
- [X] V1.66.2
- [ ] V1.62
- [ ] V1.61
- [ ] V1.60

#### Seed and Location
Sapphire City Possible Location #11

#### Description
The city spawns doubled on every seed tested, those being Dregora, [blank], and f***. Very laggy most of the time, likely due to broken chests. Worldedit's replace-air and regen commands don't have any lasting effect for some regen. Loaded game without any other mods and got same results. Checked two other places and it affected Pirate Port #6 but not Dearoc's Kingdom #9

![2021-03-31_20 29 45](https://user-images.githubusercontent.com/81721863/113229175-65f6f380-9264-11eb-8e12-bcc481456555.png)

If this issue is known about/resolved somehow, I couldn't find anything like this anywhere, so sorry.

**Comment by NLBlackEagle** [comment]
Hello, this issue is known but there's no mention of it on GitHub yet, until now at least. I mainly note the issues on [](https://roadmap.dregora.com/?controller=BoardViewController&action=readonly&token=faa613072bf23a92431a5afa615629caea1082bea725c7ba232bfec868fd) As you've figured the roadmap lacks availability which I will try to fix asap. ( Menu link in website should help and a mention on github readme.txt )

Regarding fixing the issue of double spawning: Currently Dregora uses the original TerrainControl method of spawning things in which is supported by OTG as well These are called Bo3's (BiomeObject version 3) I am planning on switching over to Bo4's (The newer version with + and - sides) but this means that I need to re-export all custom structures ( which are bo3's larger then 16x16 ) The plus side is that I will be able to fix the double spawning with adding a "true" somewhere in the config options of dregora, the downsides are as following:

Due to the way Bo4's work I can not have a center 16x16 structure and attach a 8x8 structure. Each part of the structure needs to be 16x16 which makes it hard to make randomized villages (Rainforest Village) Currently due to the randomization there are 10.000+ different random villages and I want to keep this more or less which is not possible unless I hand-craft like 200 different villages or make them more spacious ( Each 16x16 a different house )

Any way I do it It will take a long time to do and so now we arrive at why it will probably take even longer. When re-exporting the structures I will keep many of the old structures that i really like as they are but I will also re-do structures ( like sapphire city ) completely before re-exporting and configuring how they spawn and so on.

So yeah, with a lot of fiddling around I can either fix the sapphire city in 5 of the 10 cases it spawns in or I could spend that time making the new updated sapphire city and converting it to a bo4. I have already done some work but it is still ways from being completed but it's definitely being worked on! 

It's likely the next big update for Dregora will contain the new structures and new methods on spawning it in. But it'll probably also will take some time to get there. 

So... Short answer: It's kjnown, being worked on but will take some time to get fixed :) ( Apologies if the whole explanation was a bit too much but my work and idea's on Dregora is something I like sharing with those who end up using it.

**Comment by Merricide** [comment]
Yeah, the website was down when I was searching for it.

That's all incredibly fascinating, but I can tell it's really obnoxious.

Good luck with the transfer, I look forward to the update!

**Comment by NLBlackEagle** [comment]
Good to hear and thanks, out of curiosity is the website still down for you? ( And also after pressing CTRL+F5 to hard-refresh? )

**Comment by Merricide** [comment]
public.dregora.com is still down for me, ERR_CONNECTION_REFUSED

**Comment by NLBlackEagle** [comment]
Does the same count for the main website? https://dregora.com and even after a CTRL+F5 refresh?

**Comment by Merricide** [comment]
No, the main site is fine, it's actually how I found which specific places were doubled in the original post

**Comment by NLBlackEagle** [comment]
Thanks for clearing that out, roadmap has been added to the navbar of the main site and the public.dregora.com link should be working again in ~30 minutes or so I hope it will

**Comment by Merricide** [comment]
The roadmap's been up since it was added to the side bar, but public.dregora.com is still down, but now with DNS_PROBE_FINISHED_NXDOMAIN

**Comment by alfuken** [comment]
Just checking in to report the same issue. For me it looks a bit more diagonally staggered though:
![2021-05-07_11 06 12](https://user-images.githubusercontent.com/75377/117426755-90ebfb80-af24-11eb-94d6-5ec6a98c026a.png)

OpenTerrainGenerator-1.12.2-v9.3, Dregora-1.12.2-v1.66.2

I wanted to use the map for a little lan server, but this is game-breaking... Is there a way to disable this city generation at least for now?

**Comment by alfuken** [comment]
Or if it undisableable, maybe you can provide a seed where this city is generated properly?..

**Comment by NLBlackEagle** [comment]
> 
> 
> Just checking in to report the same issue. For me it looks a bit more diagonally staggered though:
> ![2021-05-07_11 06 12](https://user-images.githubusercontent.com/75377/117426755-90ebfb80-af24-11eb-94d6-5ec6a98c026a.png)
> 
> OpenTerrainGenerator-1.12.2-v9.3, Dregora-1.12.2-v1.66.2
> 
> I wanted to use the map for a little lan server, but this is game-breaking... Is there a way to disable this city generation at least for now?

The infamous double spawn issue only really has one fix which require a total revamp of the spawning system, Other fixes such as different seeds and painting in the biome that spawns it in a bit smaller have worked in the past but not in all cases. So to start with I'll explain how to completely disable these cities whereafter ill explain a possible fix that may or may not work.

For modded MC navigate to the folder /Minecraft/Mods/OpenTerrainGenerator/Worlds/Dregora/WorldBiomes/
For spigot MC navigate to the folder /Minecraft/Plugins/OpenterrainGenerator/Worlds/Dregora/WorldBiomes/

Then open the file: Dregora_OceanCityBo3.bc and replace the following string: **CustomStructure(Sap53,100.0)** with:
**CustomStructure()** Then after regenerating the world there wont be any of those cities anymore.

The other solution is to navigate to the Dregora Folder again and open the map.png then look for these green little dots:
![afbeelding](https://user-images.githubusercontent.com/4073584/117454550-8e020280-af46-11eb-9d2a-8ce3cb257d35.png)

And replace the green little dots with the color that is right next to it. Do make sure it is absolutely the same color by using a color picking tool. The result should then look like this:

![afbeelding](https://user-images.githubusercontent.com/4073584/117454820-d6212500-af46-11eb-89bd-cb97d7a6a489.png)
Make sure to save as map.png and travel to the location on the map using https://dregora.com/maps to verify it has worked.

This method will require some fiddeling around, so possibly multiple attempts to work and may not even completely work in the end. If some cities just dont want to spawn in correctly then erasing the green dots that represent those cities will do the job.

Here are the city possible locations: ( They have like 30% chance to spawn at each location )
/tp 5692 150 -6246
/tp -5897 150 -6791
/tp -7779 150 1622
/tp -4246 150 1581
/tp 3959 150 -269

![afbeelding](https://user-images.githubusercontent.com/4073584/117455843-dbcb3a80-af47-11eb-97dc-662816c85e9e.png)

These solutions are well, annoying to have for both me as those who have to end up using them but fixing them wont be a easy task and as I need to re-import all of my big structures I decided to re-make the whole city rather then trying to fix it time upon time only to have it broken on release again in some way or form.

So yeah, apologies for the rather sloppy way of walking around the bush for the time being but improvement is coming! Here's a teaser:

![afbeelding](https://user-images.githubusercontent.com/4073584/117456715-cb678f80-af48-11eb-9766-119e293bec5e.png)

**Comment by alfuken** [comment]
Looks impressive! Looking forward to it :) For now thanks for the info, other than the city everything seems to be look pretty good 👍

**Comment by ThomasBerne** [comment]
Do you have the sapphire city world edit scheme or map so we can replace the bugged ones to the map using cheats ?

**Comment by NLBlackEagle** [comment]
> 
> 
> Do you have the sapphire city world edit scheme or map so we can replace the bugged ones to the map using cheats ?

Actually, if you replace the map.png in mods/openterraingenerator/worlds/dregora with this one: https://raw.githubusercontent.com/NLBlackEagle/Dregora/master/Dregora/map.png
They will generate correctly :) I've been working on a new build but had to do other things in between too. A new build is coming out fixing that issue and adding new biomes to the map too.

It wont be a big update but it'll be a nice one fixing this issue too altough it is a temp fix. I've already started converting everything to new formats that should deal with this issue forever but its a slow and tedious task.

**Comment by ThomasBerne** [comment]
That's awesome! It works perfectly!

**Comment by NLBlackEagle** [comment]
Issue resolved with the big structure update
